### ISSUE TITLE
There is no version specified for cassandra-driver in requires

### ISSUE THREAD

**Issue by igoraj** [gianlucaborello/cassandradump#12]
When you do install it installs `cassandra-driver==3.0.0c1` as a requirement which happens to cause errors when doing exports:

```
Traceback (most recent call last):
  File "/usr/local/bin/cassandradump", line 9, in <module>
    load_entry_point('cassandradump==0.0.1', 'console_scripts', 'cassandradump')()
  File "/usr/local/lib/python2.7/dist-packages/cassandradump.py", line 350, in main
    export_data(session)
  File "/usr/local/lib/python2.7/dist-packages/cassandradump.py", line 230, in export_data
    table_to_cqlfile(session, keyname, tablename, None, tableval, f)
  File "/usr/local/lib/python2.7/dist-packages/cassandradump.py", line 94, in table_to_cqlfile
    value_encoders = make_value_encoders(tableval)
  File "/usr/local/lib/python2.7/dist-packages/cassandradump.py", line 58, in make_value_encoders
    return dict((to_utf8(k), make_value_encoder(v.data_type.typename)) for k, v in tableval.columns.iteritems())
  File "/usr/local/lib/python2.7/dist-packages/cassandradump.py", line 58, in <genexpr>
    return dict((to_utf8(k), make_value_encoder(v.data_type.typename)) for k, v in tableval.columns.iteritems())
AttributeError: 'ColumnMetadata' object has no attribute 'data_type'
```

Manually reverting cassandra driver to 2.6.0 solves the problem.

**Comment by BackendButters** [comment]
can confirm that

**Comment by gianlucaborello** [comment]
Should be fixed with https://github.com/gianlucaborello/cassandradump/pull/13
