### ISSUE TITLE
AttributeError: 'ColumnMetadata' object has no attribute 'data_type'

### ISSUE THREAD

**Issue by ekle** [gianlucaborello/cassandradump#16]
hi,
i get an error while exporting this table with cassandra 2.1:

```
CREATE TABLE slots (
    type text,
    host text,
    count int,
    PRIMARY KEY (type,host)
 );
```

```
Exporting all keyspaces
Exporting schema for keyspace engine
Exporting data for column family engine.slots
Traceback (most recent call last):
  File "cassandradump.py", line 351, in <module>
    main()
  File "cassandradump.py", line 345, in main
    export_data(session)
  File "cassandradump.py", line 225, in export_data
    table_to_cqlfile(session, keyname, tablename, None, tableval, f)
  File "cassandradump.py", line 94, in table_to_cqlfile
    value_encoders = make_value_encoders(tableval)
  File "cassandradump.py", line 58, in make_value_encoders
    return dict((to_utf8(k), make_value_encoder(v.data_type.typename)) for k, v in tableval.columns.ite
  File "cassandradump.py", line 58, in <genexpr>
    return dict((to_utf8(k), make_value_encoder(v.data_type.typename)) for k, v in tableval.columns.ite
AttributeError: 'ColumnMetadata' object has no attribute 'data_type'
```

**Comment by awinder** [comment]
+1, having this problem as well

**Comment by krishna81m** [comment]
:+1: , same problem for this table :), there should be a way to continue/skip on error or exclude specific tables.

```

[root@d8174406546b cassandradump]# python cassandradump.py --keyspace test --export-file test.cql
Exporting schema for keyspace test
Exporting data for column family test.Instrumentation
Traceback (most recent call last):
  File "cassandradump.py", line 351, in <module>
    main()
  File "cassandradump.py", line 345, in main
    export_data(session)
  File "cassandradump.py", line 225, in export_data
    table_to_cqlfile(session, keyname, tablename, None, tableval, f)
  File "cassandradump.py", line 94, in table_to_cqlfile
    value_encoders = make_value_encoders(tableval)
  File "cassandradump.py", line 58, in make_value_encoders
    return dict((to_utf8(k), make_value_encoder(v.data_type.typename)) for k, v in tableval.columns.iteritems())
  File "cassandradump.py", line 58, in <genexpr>
    return dict((to_utf8(k), make_value_encoder(v.data_type.typename)) for k, v in tableval.columns.iteritems())
AttributeError: 'ColumnMetadata' object has no attribute 'data_type'

```

Table:

```

CREATE TABLE test."Instrumentation" (
    "Rowkey" text,
    column1 text,
    "" blob,
    PRIMARY KEY (Rowkey, column1)
) WITH COMPACT STORAGE
    AND CLUSTERING ORDER BY (column1 ASC)
    AND bloom_filter_fp_chance = 0.01
    AND caching = '{"keys":"NONE", "rows_per_partition":"NONE"}'
    AND comment = ''
    AND compaction = {'class': 'org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy'}
    AND compression = {'sstable_compression': 'org.apache.cassandra.io.compress.SnappyCompressor'}
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 5184000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';

```

**Comment by emadwill** [comment]
should be fixed in #17

**Comment by Doooooo0o** [comment]
+1 https://github.com/gianlucaborello/cassandradump/pull/17 tested and approved!

**Comment by Doooooo0o** [comment]
added a new option here also https://github.com/gianlucaborello/cassandradump/pull/18

**Comment by md2k** [comment]
Hi, Any updates, seems fixes not merged to master, have same problem with data_type.

**Comment by Doooooo0o** [comment]
???

**Comment by ekle** [comment]
meanwhile i have written a dump tool in golang which use the JSON export/import feature of CQL:
https://github.com/ekle/cassdump3 for cassandra3.x
https://github.com/ekle/cassdump3 for cassandra2.2

**Comment by gianlucaborello** [comment]
Merged the PR, sorry for the delay!
